# Generated by Django 3.1.6 on 2021-02-22 13:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customusers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='avatar',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='ava/', verbose_name='Аватарка'),
            preserve_default=False,
        ),
    ]
