# Generated by Django 3.1.6 on 2021-02-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basesite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serial',
            name='episod',
            field=models.PositiveSmallIntegerField(verbose_name='Количество Эпизодов'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='season',
            field=models.PositiveSmallIntegerField(verbose_name='Количество сезонов'),
        ),
    ]
