# Generated by Django 3.1.6 on 2021-02-22 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basesite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='email',
        ),
    ]
